function [Data, Info] = SMS_importfile(filename, startRow, endRow)
%IMPORTFILE Import numeric data from a text file as column vectors.
%   [BEEPTIMERAW,TAPTIMERAW,TAPTIME_ALIGNED,ASYNCHRONY,INTERTAPTIME,ACTURALIOI,INTERONSETINTERVAL,TAPINDICATOR]
%   = IMPORTFILE(FILENAME) Reads data from text file FILENAME for the
%   default selection.
%
%   [BEEPTIMERAW,TAPTIMERAW,TAPTIME_ALIGNED,ASYNCHRONY,INTERTAPTIME,ACTURALIOI,INTERONSETINTERVAL,TAPINDICATOR]
%   = IMPORTFILE(FILENAME, STARTROW, ENDROW) Reads data from rows STARTROW
%   through ENDROW of text file FILENAME.
%
% Example:
%   [BeepTimeRaw,TapTimeRaw,TapTime_Aligned,Asynchrony,InterTapTime,ActuralIOI,InterOnsetInterval,TapIndicator]
%   = importfile('EEG1_P10_IsocA_YM11.txt',1, 64);
%
%    See also TEXTSCAN.

% Auto-generated by MATLAB on 2015/10/30 17:51:44
fprintf('\n \n-- Loading %s \n',filename);

%% Initialize variables.
delimiter = '\t';
if nargin<=2
    startRow = 1;
    endRow = 64;
end

%% Read columns of data as strings:
% For more information, see the TEXTSCAN documentation.
formatSpec = '%s%s%s%s%s%s%s%s%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to format string.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
textscan(fileID, '%[^\n\r]', startRow(1)-1, 'ReturnOnError', false);
dataArray = textscan(fileID, formatSpec, endRow(1)-startRow(1)+1, 'Delimiter', delimiter, 'ReturnOnError', false);
for block=2:length(startRow)
    frewind(fileID);
    textscan(fileID, '%[^\n\r]', startRow(block)-1, 'ReturnOnError', false);
    dataArrayBlock = textscan(fileID, formatSpec, endRow(block)-startRow(block)+1, 'Delimiter', delimiter, 'ReturnOnError', false);
    for col=1:length(dataArray)
        dataArray{col} = [dataArray{col};dataArrayBlock{col}];
    end
end

%% Close the text file.
fclose(fileID);

%% Convert the contents of columns containing numeric strings to numbers.
% Replace non-numeric strings with NaN.
raw = repmat({''},length(dataArray{1}),length(dataArray)-1);
for col=1:length(dataArray)-1
    raw(1:length(dataArray{col}),col) = dataArray{col};
end
numericData = NaN(size(dataArray{1},1),size(dataArray,2));

for col=[1,2,3,4,5,6,7,8]
    % Converts strings in the input cell array to numbers. Replaced non-numeric
    % strings with NaN.
    rawData = dataArray{col};
    for row=1:size(rawData, 1);
        % Create a regular expression to detect and remove non-numeric prefixes and
        % suffixes.
        regexstr = '(?<prefix>.*?)(?<numbers>([-]*(\d+[\,]*)+[\.]{0,1}\d*[eEdD]{0,1}[-+]*\d*[i]{0,1})|([-]*(\d+[\,]*)*[\.]{1,1}\d+[eEdD]{0,1}[-+]*\d*[i]{0,1}))(?<suffix>.*)';
        try
            result = regexp(rawData{row}, regexstr, 'names');
            numbers = result.numbers;
            
            % Detected commas in non-thousand locations.
            invalidThousandsSeparator = false;
            if any(numbers==',');
                thousandsRegExp = '^\d+?(\,\d{3})*\.{0,1}\d*$';
                if isempty(regexp(thousandsRegExp, ',', 'once'));
                    numbers = NaN;
                    invalidThousandsSeparator = true;
                end
            end
            % Convert numeric strings to numbers.
            if ~invalidThousandsSeparator;
                numbers = textscan(strrep(numbers, ',', ''), '%f');
                numericData(row, col) = numbers{1};
                raw{row, col} = numbers{1};
            end
        catch me
        end
    end
end


%% Replace non-numeric cells with NaN
R = cellfun(@(x) ~isnumeric(x) && ~islogical(x),raw); % Find non-numeric cells
raw(R) = {NaN}; % Replace non-numeric cells

%% Allocate imported array to column variable names
BeepTime = cell2mat(raw(3:end, 1));
TapTimeRaw = cell2mat(raw(3:end, 2));
TapTime_Aligned = cell2mat(raw(3:end, 3));
Asynchrony = cell2mat(raw(3:end, 4));
ITI = cell2mat(raw(3:end, 5));
Programmed_IOI = cell2mat(raw(3:end, 6));
IOI = cell2mat(raw(3:end, 7));
NoTap = cell2mat(raw(3:end, 8));

Data = table(BeepTime,TapTime_Aligned,Asynchrony,ITI,Programmed_IOI,IOI,NoTap);

TrialNumber = str2num(dataArray{1,1}{1}) + 1;
Alpha = str2num(dataArray{1,2}{1});
Difficulty = str2num(dataArray{1,3}{1});

Info = table(TrialNumber,Alpha,Difficulty);
